// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET_Developer_Intern_API_Coding_Assessment.Data;

#nullable disable

namespace NET_Developer_Intern_API_Coding_Assessment.Migrations
{
    [DbContext(typeof(AssesmentDbContext))]
    partial class AssesmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NET_Developer_Intern_API_Coding_Assessment.Model.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformInfoId");

                    b.ToTable("jobRequests");
                });

            modelBuilder.Entity("NET_Developer_Intern_API_Coding_Assessment.Model.PlatformInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CharacterLimit")
                        .HasColumnType("int");

                    b.Property<string>("PlatformName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("platformInfos");
                });

            modelBuilder.Entity("NET_Developer_Intern_API_Coding_Assessment.Model.JobRequest", b =>
                {
                    b.HasOne("NET_Developer_Intern_API_Coding_Assessment.Model.PlatformInfo", "Platforminfo")
                        .WithMany("jobRequests")
                        .HasForeignKey("PlatformInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platforminfo");
                });

            modelBuilder.Entity("NET_Developer_Intern_API_Coding_Assessment.Model.PlatformInfo", b =>
                {
                    b.Navigation("jobRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
